services:
  redis:
    image: redis:7-alpine
    container_name: test_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7
    container_name: test_mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  redis_data:
  mongodb_data: