// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProductDto = { _id: string, name: string | null, price: number | null, description: string | null, images: Array<string> | null, discount: number | null, 
/**
 * 0: Helmet
 * 1: Bike
 */
category: number | null, };
