// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInfo } from "./UserInfo.d";

export type AuthResponse = { access_token: string, refresh_token: string, user: UserInfo, };
