// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProductDto = { name: string, price: number, description: string, images: Array<string>, discount: number, 
/**
 * 0: Helmet
 * 1: Bike
 */
category: number, };
