// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role.d";

export type UserInfo = { id: string, email: string, name: string, role: Role, };
