// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

export type Product = { _id: string, name: string, price: number, description: string, images: Array<string>, discount: number, category: Category, };
