// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOrderDto = { _id: string, 
/**
 * products id
 */
products_id: Array<string> | null, total_price: number | null, };
